### ISSUE TITLE
Save and show time of completion for the completed task bag?

### ISSUE THREAD

**Issue by AlexLMeow** [cs2103aug2015-w11-3j/main#109]

**Comment by KenLSM** [comment]
Another variable to track?
What what use? (need to justify in design)
How to show? (enough space?)

**Comment by AlexLMeow** [comment]
To order the completed tasks so user can see the latest ones completed easily?

**Comment by KenLSM** [comment]
@onizudango  do we have screen space for this?

**Comment by KenLSM** [comment]
As discussed during meetings, this feature would be shelved.
