### ISSUE TITLE
Update user guide to -> date parsing incomplete hh:mm will result in default time generated

### ISSUE THREAD

**Issue by KenLSM** [cs2103aug2015-w11-3j/main#134]
update 3 start 2015-11-07, 8
gives
2015-11-07, default time

**Comment by AlexLMeow** [comment]
Known issue, I'm still finalising the partial datestring parsing policy, let you know when done.

**Comment by KenLSM** [comment]
Please note that this is not in the regression test cases.

**Comment by AlexLMeow** [comment]
Ok, I will go through your test cases when I update the date parsing policy and update them too
