### ISSUE TITLE
Support for whole day events

### ISSUE THREAD

**Issue by KenLSM** [cs2103aug2015-w11-3j/main#137]

**Comment by AlexLMeow** [comment]
We will have to decide: 
- how WDEs (Whole Day Events) are visually represented in UI.
- how we will determine if an existing task is a WDE for Logic (a new field? specific start/end values?)
- how to handle changing tasks into or away from WDEs (Logic, Parser)
- any special add/edit command formats for WDEs (Parser)

**Comment by KenLSM** [comment]
Feature Dropped.
