### ISSUE TITLE
Feedback(UI : Tabs to be placed on left side

### ISSUE THREAD

**Issue by KenLSM** [cs2103aug2015-w11-3j/main#146]
1 user claimed that users looks from left to right. Thus tabs should be on right.

Team's comment:
Ken: Looks fine being at the right side.
@YijinL 
@liuyang1213

**Comment by liuyang1213** [comment]
Personally I think left is better

**Comment by AlexLMeow** [comment]
Normally logo is on the left, so I'm fine

**Comment by KenLSM** [comment]
2:1 votes. Not changing. Case closed.
