### ISSUE TITLE
Notice: User can now specify custom aliases for commands.

### ISSUE THREAD

**Issue by AlexLMeow** [cs2103aug2015-w11-3j/main#154]
<strong>Base format to add/overwrite alias:</strong>

```
alias <target command> <new alias string>
// You can think of it as "make a new alias for <first arg>, which is <second arg>"

<target command> = 
any of the existing command aliases in the top part (CMD_*) of parser/Aliases.java

<new alias string> = any string of characters without whitespace
```

<strong>Format to clear all aliases</strong>

```
alias clear
alias null
alias empty
alias none
alias remove
alias reset
```

<strong>Examples:</strong>

```
alias add potato
```

"potato" is now recognised as a command keyword for the add action.

```
alias potato potato1
```

Will not work, you cannot chain aliases (cannot have custom alias be a target of another alias)

```
alias delete add
```

 "add" now acts as a delete command, so you can use alias to overwrite existing keywords.

```
alias add isthisdeleteoradd=]???
```

"isthisdeleteoradd=]???"  now points to Command.Type.ADD. As you can see, the original meaning of add is preserved when using it as the target of an alias. This prevents confusion if the user accidentally overwrites a base command since the base command still acts normally when being an alias target.

```
alias mark potato
```

"potato" has been retargetted to mark. (the old target was add)

```
alias quit alias
```

Will not work: you cannot use "alias" as an alias. This is to prevent the user from aliasing themselves away from all commands. 
Eg. Damith aliases everything to "quit". Still can revert with "alias clear"

```
alias alias cat
```

This works. cat now refers to alias.

```
map add myadd
shortcut add myadd
point quit myquit
-> edit myEdit
```

Besides using "alias", you can use these command tokens for aliasing as well. Of course you can also set your own custom aliases.

```
-> undo CAPS_UNDO

caps_undo   // performs undo
CaPs_uNdO   // performs undo
```

Aliases are never case sensitive (like the default parser aliases)

<strong>Changes</strong>

<strong>Storage/common:</strong> common.Configuration
    Added full reading and storing logic. Your aliases will persist across sessions.
    I marked my additions with //TODO so you can take a look. I followed the format
    of the other methods.

<strong>Logic:</strong> logic.AliasAction (new)
    Not undoable. Provides warning when trying to use "alias" as your own custom alias.

<strong>UI: </strong> ui.view.CelebiViewController
    Syntax highlighting now updates for custom aliases instantly.

**Comment by AlexLMeow** [comment]
Go try it pls.

@liuyang1213  @KenLSM  @onizudango

**Comment by AlexLMeow** [comment]
Any bugs put here. I already tested a lot though...

**Comment by liuyang1213** [comment]
Emm, I think we should prevent the built-in keywords from being overwritten

**Comment by liuyang1213** [comment]
```
alias delete add
alias add isthisdeleteoradd=]???
```

It is a bit confusing I think

**Comment by liuyang1213** [comment]
Very good job! 辛苦了 :)

**Comment by AlexLMeow** [comment]
@liuyang1213  @KenLSM  @onizudango 

User now cannot use reserved keywords as aliases.
Reserved keywords are shown in the "help" command.
The keywords shown in the "help" command will always work as intended.
