### ISSUE TITLE
What's Up Tab: Discussion

### ISSUE THREAD

**Issue by AlexLMeow** [cs2103aug2015-w11-3j/main#158]
@KenLSM  @liuyang1213  @onizudango

**Comment by KenLSM** [comment]
Purpose: What is currently happening that requires your attention the most.

Ken: Iif the event is occurring now or is going to occur soon, it should be on the list
Therefore it is obtained by
Dated tasks that has anydate(end date first). The date should be between now and X number of days in the future.

**Comment by liuyang1213** [comment]
For events with only start date, I think if it is passed, user will mark them as done, otherwise should be ongoing

**Comment by KenLSM** [comment]
So new rule is to add tasks which have startdates only?

**Comment by AlexLMeow** [comment]
We also support start-date only tasks, what's the policy?

What's the use case for start-only tasks anyway?

**Comment by KenLSM** [comment]
Post 2103 Celebration | started from last monday

**Comment by AlexLMeow** [comment]
Then theres no specified end, let the user choose when they want to close it.

Let's treat it like a deadline for all sorting, filtering, graying out.
And let it show in What's Up too

**Comment by KenLSM** [comment]
Fixed
