### ISSUE TITLE
DG: Individual component parts

### ISSUE THREAD

**Issue by AlexLMeow** [cs2103aug2015-w11-3j/main#160]
@KenLSM  @liuyang1213  @onizudango 

Let's standardise our Parts.

<strong>Diagrams:</strong>
- A class diagram covering the entire component (exclude data holding classes)
- A sequence diagram for the most common use case of your component.
- (optional) any other diagrams to explain complicated parts of your component

<strong>Sections:</strong>
- Each notable class should have a section
- Exclude data holding classes
- Include notable APIs (methods that other classes have to call in the workflow)
- A nice explanation

Due Sunday 5pm so I can merge all.

**Comment by AlexLMeow** [comment]
Close your individual DG issues when done

**Comment by AlexLMeow** [comment]
Remember to talk about any design patterns if you have used them.

Eg Singleton, Command

And justify it.

**Comment by AlexLMeow** [comment]
#86 #87 #88 #89

**Comment by liuyang1213** [comment]
Are we going to show public methods? No private data/methods?

**Comment by liuyang1213** [comment]
@YijinL
