### ISSUE TITLE
DevGuide: updated UML diagrams (class, sequence) for Logic

### ISSUE THREAD

**Issue by AlexLMeow** [cs2103aug2015-w11-3j/main#88]

**Comment by AlexLMeow** [comment]
For yours, you just need specialised sections for the ActionInvoker and Logic.

Then have a section on Action interface and UndoableAction interface where you explain what they do (APIs too)
And list all the Action classes that implement them and roughly how they work.

Don't need to do too much.

**Comment by AlexLMeow** [comment]
and CommandFeedback.

and any special exceptions that will be thrown out of logic component

**Comment by AlexLMeow** [comment]
1. Logic
2. CommandFeedback
3. ActionInvoker
4. Action
5. UndoableAction
6. (optional) any exceptions thrown out of logic component
7. LogicTest

Follow this order to show top-down approach.
For the notable APIs part, if the class has an interface then list those methods, else only the ones that are used by other classes.

For the testing classes, just instructions on how to set up and start testing.
And % coverage (if applicable) and a brief description on what you cover.

**Comment by KenLSM** [comment]
For the Undoable action, im moving them to appendices along with normal actions themselves as they dont need much details to understand their purpose. Notable apis has also been combined into Logic to explain the facade class.

**Comment by KenLSM** [comment]
I have completed my portion of the docs.
The pages of concern are
Bottom image of page 27 (Updated to a proper sequence diagram)
Logic components page 32 - 35 (the {something} represents annexes or appendices)
